say:
  description: Make a Jibo robot say something.
  fields:
    message:
      description: The text to speak.
      example: "Hello, Home Assistant!"
      required: true
      selector:
        text:
    robot:
      description: >
        Name of the robot to speak on. Leave empty to speak on all configured
        Jibo robots.
      example: "Living Room Jibo"
      required: false
      selector:
        text:
